version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - go_todo_gin_db:/var/lib/postgresql/data/

volumes:
  go_todo_gin_db:
